### ISSUE TITLE
Building v0.7.1 on Alma9 fails with -fPIC errors

### ISSUE THREAD

**Issue by jsonstro** [esnet/EScp#3]
Hi ESNet folks,

I've been trying to build EScp on Alma9 using the OS rust and gcc 11.4.1. It errors out in the linking phase:

   Compiling escp v0.7.1 (/hb/home/jsonstro/EScp)
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/usr/lib/rustlib/x86_64-unknown-linux-gnu/bin:/root/.cargo/bin:/hb/software/spack/linux-almalinux9-cascadelake/gcc-11.4.1/cmake-3.26.5-zkyebsgiokmyhoxy7qwe2nqdwd4mmf6x/bin:/hb/software/utils/miniconda3/condabin:/opt/ohpc/admin/spack/0.21.2/bin:/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin" VSLANG="1033" "cc" "-m64" "/tmp/rustcK4n2zy/symbols.o" "/hb/home/jsonstro/EScp/target/release/deps/escp-8216f89941210f3e.escp.c4fbb1143e98c84d-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/hb/home/jsonstro/EScp/target/release/deps" "-L" "/hb/home/jsonstro/EScp/target/release/build/libgit2-sys-dcaf4bf67eecee80/out/build" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/rustcK4n2zy/liblibgit2_sys-e0b757b8db1fbc00.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-ac797ffc66992bc1.rlib" "-Wl,-Bdynamic" "-lz" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/hb/home/jsonstro/EScp/target/release/deps/escp-8216f89941210f3e" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,--strip-all" "-nodefaultlibs" "build/libdtn.a" "build/isal/lib/libisal_crypto.a" "build/libnuma/lib/libnuma.a" "-lrt" "-lc"
  = note: /usr/bin/ld: build/libnuma/lib/libnuma.a(libnuma.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIE
          /usr/bin/ld: build/libnuma/lib/libnuma.a(affinity.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
          collect2: error: ld returned 1 exit status

I was able to get it to this point by adding "-fPIE" to the CMAKE_C_FLAGS_RELEASE variable in libdtn/CMakeLists.txt

set(CMAKE_C_FLAGS_RELEASE "-g -march=sandybridge -pthread -fPIE -O ")

However, I can't seem to get past this error. Any ideas?'

thanks,
josh

**Comment by cbears** [comment]
Hi Josh, 

I updated the build files to "do the right thing (tm)", and things should just work if you try the latest commit. I also updated the README with better instructions on how to build against the RedHat family. If things don't work correctly by running `./mk.sh`, go ahead and delete the entire tree and re-check it out.

A lot of things happen automagically during the build process, and somehow rust and possibly CMake defaulted to building in PIE mode based on the toolchain options presented by RedHat families. Usually this is great as PIE is better, but, because we are asking the linker to statically link to libraries that default breaks things as PIE is not compatible with statically linking (in most cases).

Thanks for letting me know about the bug, and please go ahead and re-open the issue if this does not fix things,
Charles

**Comment by jsonstro** [comment]
Hi Charles,

Thank you so much for the followup. I was now able to successfully compile, link, build and install the RPM. My only remaining recommendation in terms of documentation is to add a line for the local RPM install with dnf like so:

dnf install target/release/rpmbuild/RPMS/x86_64/escp-0.8.0-1.el9.x86_64.rpm

We can close this out as complete!

Kind regards,
Josh
